version: '3.8'


services:
  db:
    image: postgres:14.3
    restart: on-failure
    ports:
      - "9432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: teslodb
    volumes:
      - ./postgres:/var/lib/postgresql/data
  